### ISSUE TITLE
if I use Jcrop on compression picture

### ISSUE THREAD

**Issue by riskers** [tapmodo/Jcrop#171] opened 2015-01-06 06:20 UTC
if I have a picture, it's width is 1280px ,but picture's contain's width is 550px . 
I use Jcrop on the contain , then I crop this picture , I found the coordinates is fuck error .

How could I do ?

**Comment by tapmodo** [comment] 2015-09-01 00:52
Sounds like you're doing something that is messing with Jcrop. The issue is not clear. I'm going to close this issue now, but if you have more information or can re-state the question please open a new issue. Thanks!

**Closed by tapmodo** 2015-09-01 00:52 UTC
