### ISSUE TITLE
Setting Options in cropmove event causes stack limit exception

### ISSUE THREAD

**Issue by sewpafly** [tapmodo/Jcrop#203] opened 2015-08-26 21:51 UTC
It appears that listening on the `cropmove` event, and then settting an option in the callback (`api.setOptions()`) causes an infinite loop, triggering a stack exception when the limit is reached.

**Comment by tapmodo** [comment] 2015-09-01 00:52
Can you provide specific code to reproduce this condition? Thanks!

**Comment by sewpafly** [comment] 2015-09-09 15:23
```js
var api;

$(function(){
    $('#crop-this').Jcrop({}, function(){
        api = this
        api.container.on('cropmove', function(e,s,c){
            console.log(c)
            // if the width is less than 50 make the background red
            // else make it green
            if (c.w < 50){
                api.setOptions({'bgColor': 'red'});
            }
            else {
                api.setOptions({'bgColor': 'green'});
            }
        })
    })
})
```

See this fiddle for a working example: http://jsfiddle.net/sewpafly/kadwjac5/3/

**Comment by tapmodo** [comment] 2015-09-09 23:58
I'm not surprised this is causing a recursive looping problem. I haven't looked at the Jcrop source but I believe that it does refresh the selection after the options are set. Therefore, it's triggering the event, which triggers the options to be set again, and so on, until the stack limit is exceeded.

If you only update the options when they _change_, you can do this without killing the stack.
[See this updated fiddle.](http://jsfiddle.net/0afmrxvd/1/)

Since that code appears to work for what you're trying to do, I'm going to close the issue.

**Closed by tapmodo** 2015-09-09 23:58 UTC
