### ISSUE TITLE
Image is not visible or is displayed as dot in iphone and ipad

### ISSUE THREAD

**Issue by differenz-manan** [tapmodo/Jcrop#161] opened 2014-09-06 10:26 UTC
I have found out that When i run my application in Chrome,Firefox,IE Image is properly displayed, but in iphone and ipad ,Image is not visible properly and displayed as a small dot in both Chrome and Safari
browsers.

If anyone have found a way to this problem, please help.

Thank you in advance.

**Comment by tapmodo** [comment] 2015-09-01 00:50
Thanks for the note! I'm going to close this issue since it's not clear that it's a problem specifically related to Jcrop. Please open a new issue if the problem is persisting or if there more information is available that can lead to Jcrop code improvements.

**Closed by tapmodo** 2015-09-01 00:50 UTC
